version: '3'
services:
  proxy:
    image: nginx:stable-alpine
    ports:
      - 127.0.0.1:443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./intermediate/private/ac-demo.me.key.nopass.pem:/etc/nginx/ssl/server.key
      - ./intermediate/certs/ac-demo.me.chained.cert.pem:/etc/nginx/ssl/fullchain.pem
